[package]
name = "scaffolder"
version = "0.2.2"
compiler = "0.12.0"
repository = "https://github.com/wisp3rwind/typst-scaffolder"
entrypoint = "src/lib.typ"
authors = [
  "wisp3rwind <@wisp3rwind>"
]
categories = [ "utility", "layout" ]
license = "MIT"
description = "Show borders around the main text area, header and footer in Typst documents."
keywords = [
  "layout",
  "showframe",
  "margin",
  "header",
  "footer",
  "page",
  "margins",
]
exclude = [
  ".github",
  ".gitignore",
  "docs",
  "scripts",
  "tests",
  "Justfile",
  "CHANGELOG.md",
  "CONTRIBUTING.md",
]

[tool.tytanic]
# Account for some font rendering changes from Typst 0.12 -> 0.13 without updating the reference images
default.max-delta = 2
