[package]
name = "showframe"
version = "0.1.0"
compiler = "0.12.0"
repository = "https://github.com/wisp3rwind/typst-showframe"
entrypoint = "src/lib.typ"
authors = [
  "wisp3rwind <@wisp3rwind>"
]
categories = [ "utility", "layout" ]
license = "MIT"
description = "Show borders around the main text area, header and footer in Typst documents."
keywords = [
  "layout",
  "margin",
  "header",
  "footer",
]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  "Justfile",
]
