name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-examples:
    strategy:
      matrix:
        typst-version: ["0.12", "0.13", "0.14", "latest"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: ${{ matrix.typst-version }}
          allow-prereleases: true

      - name: Build examples
        run: just examples

  reftests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # tytanic is based on the following Typst versions
        # - 0.1.z -> 0.12
        # - 0.2.z -> 0.13
        # - 0.3.z -> 0.14
        # cf. https://typst-community.github.io/tytanic/reference/compat.html
        tytanic-version: ["0.1", "0.2", "0.3"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: taiki-e/install-action@v2
        with:
          tool: tytanic@${{ matrix.tytanic-version }}

      - name: Run test suite
        run: tt run

      - name: Archive diffs
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: typst-${{ matrix.tytanic-version }}-diffs
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 14
